#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pz deps/setup/ebin

-mode(compile).

main(Opts) ->
    try setup_gen:run([
		       {name, "exodm"},
		       {relconf, "rel/reltool.config"},
		       {sys, "rel/sys.config"},
		       {outdir, "./devel"},
		       {install, true},
		       {verbose, true},
		       {env, [
			      {setup,
			       [
				{data_dir, "db"}
			       ]}
			     ]}
		       | opts(Opts)
		      ])
    catch
	error:E ->
	    io:fwrite("ERROR: ~p~n"
		      "Trace: ~p~n", [E, erlang:get_stacktrace()]),
	    timer:sleep(500),
	    halt(1)
    end.

opts(["-target","false"]) ->
    [{target, false}];
opts(["-target", T]) ->
    [{target, T}];
opts([]) ->
    [].

